apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: construction-cost-model
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaispace30098/construction-cost-gitops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
